# Kubernetes workflow Dotbot config
- defaults:
    link:
      ignore-missing: true
      relink: true
      create: true
      force: true
    shell:
      stdout: true

- shell:
    # Bootstrap Kubernetes CLI tools
    - [ "./workflows/kubernetes/install.sh", "bash -lc" ]

- link:
    # Link a base kubeconfig (edit with your clusters)
    ~/.kube/config: workflows/kubernetes/config